services:
  php:
    volumes:
      - ./:/app:delegated
      - ./.docker/vendor-cache/php${PHP_VERSION}:/app/vendor
      - ./docker/php/${PHP_VERSION}/phpunit.xml:/app/phpunit.xml
    build:
      context: ./docker/php/${PHP_VERSION-7.1}
      target: base
    env_file:
      - .env

  debug:
    volumes:
      - ./:/app:delegated
      - ./.docker/vendor-cache/php${PHP_DEBUG}:/app/vendor
      - ./docker/php/${PHP_DEBUG}/phpunit.xml:/app/phpunit.xml
      - ./docker/php/${PHP_DEBUG}/conf:/usr/local/etc/php
    build:
      context: ./docker/php/${PHP_DEBUG-7.1}
      target: debug
    env_file:
      - .env

  composer:
    volumes:
      - ./:/app:delegated
      - ./.docker/vendor-cache/php${PHP_COMPOSER}:/app/vendor
    build:
      context: ./docker/php/${PHP_COMPOSER-7.1}
      target: composer
    env_file:
      - .env

networks:
  default:
    driver: bridge
    labels:
      auto-remove: "true"