name: tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: ["7.1"]

    steps:
      - uses: actions/checkout@v4

      - name: Create .env
        run: touch .env

      - name: Set environment for PHP ${{ matrix.php-version }}
        run: |
          echo "PHP_COMPOSER=${{ matrix.php-version }}" >> $GITHUB_ENV
          echo "PHP_VERSION=${{ matrix.php-version }}" >> $GITHUB_ENV
          echo "PHPUNIT_DIR=tests/config" >> $GITHUB_ENV

      - name: Install dependencies (composer update) for PHP ${{ matrix.php-version }}
        run: |
          docker compose run install
          rm composer.lock
          docker compose run --rm composer composer install

      - name: Run PHPUnit tests for PHP ${{ matrix.php-version }}
        run: docker compose run --rm php ./vendor/bin/phpunit --configuration "/app/tests/config/${{ matrix.php-version }}/phpunit.xml"